version: '3.8'

services:
    redis:
        image: redis:latest
        container_name: redis
        ports:
            - '6379:6379'

    postgres:
        image: postgres:latest
        container_name: postgres
        environment:
            POSTGRES_PASSWORD: 'Admin123!!'
        ports:
            - '5432:5432'
