version: '3.8'

services:
    redis:
        image: redis:latest
        container_name: redis
        ports:
            - '6679:6379'

    postgres:
        image: postgres:latest
        container_name: postgres
        environment:
            POSTGRES_PASSWORD: 'Admin123!!'
            POSTGRES_USER: 'postgres'
            POSTGRES_DB: 'postgres'
        ports:
            - '6432:5432'
